Repository SOPT-all/35-APPJAM-iOS-MEMENTO, pull requests merged in 2025-01, with the labels that each got.

#3 [Setting] #1 - Initial setting
  Memento-iOS/Memento-iOS.xcodeproj/project.pbxproj
  Memento-iOS/Memento-iOS.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Memento-iOS/Memento-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Memento-iOS/Memento-iOS/Preview Content/Preview Assets.xcassets/Contents.json
  Memento-iOS/Memento-iOS/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  Memento-iOS/Memento-iOS/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Memento-iOS/Memento-iOS/Resource/Assets.xcassets/Contents.json
  Memento-iOS/Memento-iOS/Source/App/Config.swift
  Memento-iOS/Memento-iOS/Source/App/Memento_iOSApp.swift
  Memento-iOS/Memento-iOS/Source/Extension/Date+.swift
  Memento-iOS/Memento-iOS/Source/Extension/View+.swift
  Memento-iOS/Memento-iOS/Source/Network/Base/BaseAPIService.swift
  Memento-iOS/Memento-iOS/Source/Network/Base/BaseDTO.swift
  Memento-iOS/Memento-iOS/Source/Network/Base/NetworkService.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Today/View/TodayView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Today/ViewModel/TodayViewModel.swift
Labels: Setting, 가현

#4 [Feat] #2 - Custom TabBar
  Memento-iOS/Memento-iOS/Source/Component/TabBar/TabBarItem.swift
  Memento-iOS/Memento-iOS/Source/Component/TabBar/TabBarView.swift
Labels: Feat, 가현

#6 [Feat] #5 - Today view sticky header, list cell
  Memento-iOS/Memento-iOS/Source/Component/MementoCell/ColorTagView.swift
  Memento-iOS/Memento-iOS/Source/Component/MementoCell/PriorityLabel.swift
  Memento-iOS/Memento-iOS/Source/Component/MementoCell/ScheduleListCell.swift
  Memento-iOS/Memento-iOS/Source/Component/MementoCell/TodoListCell.swift
  Memento-iOS/Memento-iOS/Source/Extension/Color+.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Today/View/AllDayCell.swift
Labels: Feat, 가현

#11 [Feat] #8 - Design system SPM setting
  Memento-iOS/Memento-iOS.xcodeproj/project.pbxproj
  Memento-iOS/Memento-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Memento-iOS/Memento-iOS/Source/Component/MementoCell/PriorityLabel.swift
  Memento-iOS/Memento-iOS/Source/Component/MementoCell/ScheduleListCell.swift
  Memento-iOS/Memento-iOS/Source/Component/MementoCell/TodoListCell.swift
  Memento-iOS/Memento-iOS/Source/Const/StringLiteral.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Today/View/TodayListView.swift
Labels: Setting, 가현

#12 Feat/#9 create onboarding view
  Memento-iOS/Memento-iOS.xcodeproj/project.pbxproj
  Memento-iOS/Memento-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Memento-iOS/Memento-iOS/Source/App/Memento_iOSApp.swift
  Memento-iOS/Memento-iOS/Source/Component/BackgroundView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/Model/Category.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/View/Component/StepProgressBar.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/View/LoginView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/View/SleepCycleSettingView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/View/WorkSelectionView.swift
Labels: Add

#14 [Feat] #10 - Todo List View
  Memento-iOS/Memento-iOS/Source/Presentation/ToDoList/View/ToDoListView.swift
Labels: Feat, 세민

#20 [Hotfix] #19 - error fix
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/View/LoginView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/ToDoList/View/ToDoListView.swift
Labels: 가현, Hotfix

#28 [Feat] #15 - Cell & Label
  Memento-iOS/Memento-iOS.xcodeproj/project.pbxproj
  Memento-iOS/Memento-iOS/Source/App/AppDelegate.swift
  Memento-iOS/Memento-iOS/Source/Component/MementoCell/PriorityLabel.swift
  Memento-iOS/Memento-iOS/Source/Component/MementoCell/ScheduleListCell.swift
  Memento-iOS/Memento-iOS/Source/Component/MementoCell/TodoListCell.swift
  Memento-iOS/Memento-iOS/Source/Presentation/ToDoList/View/ToDoListView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Today/Model/ScheduleDataModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Today/View/TodayListView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Today/ViewModel/TodayViewModel.swift
Labels: Feat, Fix, 세민

#32 [Feat] #22 - MCalendar 연결 및 All-day header
  Memento-iOS/Memento-iOS.xcodeproj/project.pbxproj
  Memento-iOS/Memento-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Memento-iOS/Memento-iOS/Source/Component/TabBar/TabBarItem.swift
  Memento-iOS/Memento-iOS/Source/Data/MCalendarEventList.swift
  Memento-iOS/Memento-iOS/Source/Data/MEventDataSource.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Today/Model/AllDayDataModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Today/View/AllDayCell.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Today/View/AllDayListView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Today/View/OffsetObservableScrollView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Today/View/TodayListView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Today/View/TodayView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Today/View/WeeklyCalendarView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Today/ViewModel/WeeklyCalendarViewModel.swift
Labels: Feat, 가현

#36 [Feat] #33 - EmptyView, Alert
  Memento-iOS/Memento-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Memento-iOS/Memento-iOS/Source/Component/Alert/ScheduleAlertView.swift
  Memento-iOS/Memento-iOS/Source/Component/Alert/TodoAlertView.swift
  Memento-iOS/Memento-iOS/Source/Const/StringLiteral.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Today/View/EmptyView.swift
Labels: Feat, 가현

#40 [ Hotfix] #39 - pbx file fix
  Memento-iOS/Memento-iOS.xcodeproj/project.pbxproj
Labels: 가현, Hotfix

#38 [Feat] #16 - Segmented Menu View
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/SegmentedMenu/Model/SegmentedMenuType.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/SegmentedMenu/View/SegmentedMenuView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/SegmentedMenu/ViewModel/SegmentedMenuViewModel.swift
Labels: Feat, 범수

#45 [Hotfix] #44 - pbx file fix
  Memento-iOS/Memento-iOS.xcodeproj/project.pbxproj
  Memento-iOS/Memento-iOS/Source/Const/StringLiteral.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Today/View/AllDayCell.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Today/View/ArrowListCell.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Today/View/ReusableView/WakeUpHeaderView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Today/View/ReusableView/WindDownFooterView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Today/View/TodayListView.swift
Labels: 가현, Hotfix

#42 Feat/#37 AI Neon Animation View 구현
  Memento-iOS/Memento-iOS.xcodeproj/project.pbxproj
  Memento-iOS/Memento-iOS/Source/Component/NeonAnimationView.swift
  Memento-iOS/Memento-iOS/Source/Component/ResponsiveAnimationView.swift
Labels: Feat, 정욱

#47 [Feat] #41 - Progress state bar
  Memento-iOS/Memento-iOS.xcodeproj/project.pbxproj
  Memento-iOS/Memento-iOS/Source/Component/ResponsiveAnimationView.swift
Labels: Feat, 가현

#46 [Refactor] #29 - Today / ToDoList 뷰 ViewModel 개선
  Memento-iOS/Memento-iOS.xcodeproj/project.pbxproj
  Memento-iOS/Memento-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Memento-iOS/Memento-iOS/Source/Component/MementoCell/AllDayListCell.swift
  Memento-iOS/Memento-iOS/Source/Component/MementoCell/ColorTagView.swift
  Memento-iOS/Memento-iOS/Source/Component/MementoCell/PriorityLabel.swift
  Memento-iOS/Memento-iOS/Source/Component/MementoCell/ScheduleListCell.swift
  Memento-iOS/Memento-iOS/Source/Component/MementoCell/ToDoListCell.swift
  Memento-iOS/Memento-iOS/Source/Component/MementoCell/TodoListCell.swift
  Memento-iOS/Memento-iOS/Source/Component/TabBar/TabBarItem.swift
  Memento-iOS/Memento-iOS/Source/Extension/Color+.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/Model/AllDayListDataModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/Model/ScheduleListDataModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/Model/ToDoListDataModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/Model/TodayItemDataModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/View/ArrowListCell.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/View/OffsetObservableScrollView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/View/ReusableView/WakeUpHeaderView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/View/ReusableView/WindDownFooterView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/View/ToDoList/ToDoListView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/View/Today/AllDayListView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/View/Today/EmptyView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/View/Today/TodayView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/View/Today/TodayWeeklyCalendarView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/ViewModel/ToDoListViewModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/ViewModel/WeeklyCalendarViewModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/ToDoList/View/ToDoListView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Today/Model/TodoDataModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Today/View/AllDayCell.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Today/View/OffsetObservableScrollView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Today/ViewModel/TodayViewModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Today/ViewModel/WeeklyCalendarViewModel.swift
Labels: Refactor, 세민

#52 [Feat] #43 - BrainDumpView 구현
  Memento-iOS/Memento-iOS.xcodeproj/project.pbxproj
  Memento-iOS/Memento-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Memento-iOS/Memento-iOS/Source/Component/BackgroundView.swift
  Memento-iOS/Memento-iOS/Source/Component/CustomTextEditor.swift
  Memento-iOS/Memento-iOS/Source/Component/NeonAnimationView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/BrainDump/View/BrainDumpView.swift
Labels: Feat, 정욱

#57 [Feat] #50 - Repeated schedule deleted, edited alert
  Memento-iOS/Memento-iOS.xcodeproj/project.pbxproj
  Memento-iOS/Memento-iOS/Source/Component/Alert/CustomActionSheetView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/Model/ScheduleListDataModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/View/Today/TodayView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/ViewModel/WeeklyCalendarViewModel.swift
Labels: Feat, 가현

#60 [Feat] #53 - Eisenhower Matrix View 구현
  Memento-iOS/Memento-iOS.xcodeproj/project.pbxproj
  Memento-iOS/Memento-iOS/Source/Component/EisenhowerMatrixView.swift
Labels: Feat, 정욱

#64 [Setting] #58 - Network Setting
  .gitignore
  Memento-iOS/Memento-iOS.xcodeproj/project.pbxproj
  Memento-iOS/Memento-iOS/Info.plist
  Memento-iOS/Memento-iOS/Source/App/Config.swift
  Memento-iOS/Memento-iOS/Source/Network/Base/BaseAPIService.swift
  Memento-iOS/Memento-iOS/Source/Network/Base/BaseDTO.swift
  Memento-iOS/Memento-iOS/Source/Network/Base/BaseTargetType.swift
  Memento-iOS/Memento-iOS/Source/Network/Base/MoyaPlugin.swift
  Memento-iOS/Memento-iOS/Source/Network/Base/NetworkResult.swift
  Memento-iOS/Memento-iOS/Source/Network/Base/NetworkService.swift
  Memento-iOS/Memento-iOS/Source/Network/Health/HealthCheckAPIService.swift
  Memento-iOS/Memento-iOS/Source/Network/Health/HealthCheckDTO.swift
  Memento-iOS/Memento-iOS/Source/Network/Health/HealthCheckTargetType.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/View/LoginView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/ViewModel/OnboardingViewModel.swift
Labels: Setting, 가현

#56 [Feat] #55 - Add Todo View 구현
  Memento-iOS/Memento-iOS.xcodeproj/project.pbxproj
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddTodo/View/AddTodoBottomView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddTodo/View/AddTodoHeaderView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddTodo/View/AddTodoTextView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddTodo/View/AddTodoView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddTodo/ViewModel/AddTodoHeaderViewModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddTodo/ViewModel/AddTodoTextViewModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/SegmentedMenu/View/SegmentedMenuView.swift
Labels: Feat, 범수

#59 [Feat] #51 - Add Schedule View 구현
  Memento-iOS/Memento-iOS.xcodeproj/project.pbxproj
  Memento-iOS/Memento-iOS/Source/Const/StringLiteral.swift
  Memento-iOS/Memento-iOS/Source/Extension/Date+.swift
  Memento-iOS/Memento-iOS/Source/Extension/View+.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddSchedule/Model/AddScheduleSectionType.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddSchedule/Model/DateTimeSelection.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddSchedule/Model/RepeatType.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddSchedule/View/AddEventTitleView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddSchedule/View/AddScheduleView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddSchedule/View/AllDayCheckBoxButton.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddSchedule/View/DateTimePickerSectionView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddSchedule/View/DateTimePickerView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddSchedule/View/RepeatPickerView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddSchedule/View/RepeatTypeListView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddSchedule/ViewModel/AddEventTitleViewModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/PickerButton/Model/PickerButtonType.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/PickerButton/View/PickerButton.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/PickerButton/ViewModel/BasePickerViewModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/PickerButton/ViewModel/PickerButtonViewModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/Protocols/Presentable.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/SegmentedMenu/View/SegmentedMenuView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/Sheet/BaseSheetView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/Sheet/SheetContainer.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/Sheet/SheetHeaderView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/Tag/Model/Tag.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/Tag/View/TagListItem.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/Tag/View/TagListView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/Tag/View/TagPickerButton.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/Tag/View/TagPickerSheetView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/Tag/View/TagView.swift
  Memento-iOS/Memento-iOS/Source/Utils/DynamicPresentationDetent.swift
Labels: Feat, 범수

#68 [Feat] DeadlineView 구현
  Memento-iOS/Memento-iOS.xcodeproj/project.pbxproj
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddSchedule/Model/AddScheduleSectionType.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddSchedule/Model/RepeatType.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddSchedule/View/DateTimePickerSectionView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddSchedule/View/RepeatPickerView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddSchedule/View/RepeatTypeListView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddTodo/View/AddDeadlineView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddTodo/View/AddTodoBottomView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/PickerButton/Model/PickerButtonType.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/PickerButton/View/PickerButton.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/PickerButton/ViewModel/PickerButtonViewModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/SegmentedMenu/ViewModel/SegmentedMenuViewModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/Sheet/BaseSheetView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/Sheet/SheetContainer.swift
  Memento-iOS/Memento-iOS/Source/Utils/DynamicPresentationDetent.swift
Labels: Feat, 범수

#70 [Network] #66 - Schedule API sub connect
  Memento-iOS/Memento-iOS.xcodeproj/project.pbxproj
  Memento-iOS/Memento-iOS/Source/Extension/Date+.swift
  Memento-iOS/Memento-iOS/Source/Network/Schedule/DTO/Response/DailyScheduleData.swift
  Memento-iOS/Memento-iOS/Source/Network/Schedule/DTO/Response/ScheduleAllDayResponseData.swift
  Memento-iOS/Memento-iOS/Source/Network/Schedule/DTO/Response/ScheduleTotalResponseData.swift
  Memento-iOS/Memento-iOS/Source/Network/Schedule/ScheduleAPIService.swift
  Memento-iOS/Memento-iOS/Source/Network/Schedule/ScheduleTargetType.swift
Labels: 가현, Network

#69 Refactor/#61 로그인 관련 리팩토링 및 에러 수정
  Memento-iOS/Memento-iOS.xcodeproj/project.pbxproj
  Memento-iOS/Memento-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Memento-iOS/Memento-iOS/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Memento-iOS/Memento-iOS/Resource/Assets.xcassets/AppIcon.appiconset/app_icon 1.png
  Memento-iOS/Memento-iOS/Resource/Assets.xcassets/AppIcon.appiconset/app_icon 2.png
  Memento-iOS/Memento-iOS/Resource/Assets.xcassets/AppIcon.appiconset/app_icon.png
  Memento-iOS/Memento-iOS/Source/App/Memento_iOSApp.swift
  Memento-iOS/Memento-iOS/Source/Component/TimePickerView/TimePickerView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/Model/SleepCycleRequestModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/Model/SurveyQuestion.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/View/CalendarConnectView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/View/LoginView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/View/SleepCycleSettingView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/View/WorkPreferenceView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/View/WorkSelectionView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/ViewModel/AuthViewModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/ViewModel/OnboardingViewModel.swift
Labels: Feat, 정욱

#77 [Setting] #63 - View 연결 및 탭바 디테일, 투데이 progress 세팅, AlertView 디테일 및 데이터 동기화
  Memento-iOS/Memento-iOS.xcodeproj/project.pbxproj
  Memento-iOS/Memento-iOS/Source/Component/Alert/Button/DeleteButton.swift
  Memento-iOS/Memento-iOS/Source/Component/Alert/Button/EditButton.swift
  Memento-iOS/Memento-iOS/Source/Component/Alert/ScheduleAlertView.swift
  Memento-iOS/Memento-iOS/Source/Component/Alert/ToDoAlertView.swift
  Memento-iOS/Memento-iOS/Source/Component/TabBar/TabBarItem.swift
  Memento-iOS/Memento-iOS/Source/Component/TabBar/TabBarView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddTodo/View/AddTodoBottomView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/SegmentedMenu/View/SegmentedMenuView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/View/ReusableView/WakeUpHeaderView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/View/ReusableView/WindDownFooterView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/View/ToDoList/ToDoListView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/View/Today/TodayView.swift
Labels: Feat, Setting, 세민

#75 [Feat] #74 - 투두 추가 뷰 마무리
  Memento-iOS/Memento-iOS.xcodeproj/project.pbxproj
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddTodo/View/AddTodoBottomView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddTodo/View/AddTodoHeaderView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddTodo/ViewModel/AddTodoHeaderViewModel.swift
Labels: Feat, 범수

#79 Feat/#67 TokenRefresh 로직 구현 및 추가 Onboarding 기능 구현
  Memento-iOS/Memento-iOS.xcodeproj/project.pbxproj
  Memento-iOS/Memento-iOS/Source/App/Memento_iOSApp.swift
  Memento-iOS/Memento-iOS/Source/Const/StringLiteral.swift
  Memento-iOS/Memento-iOS/Source/Network/Base/BaseTargetType.swift
  Memento-iOS/Memento-iOS/Source/Network/Base/TokenKeychainManager.swift
  Memento-iOS/Memento-iOS/Source/Network/Base/TokenRefreshPlugin.swift
  Memento-iOS/Memento-iOS/Source/Network/Onboarding/DTO/Request/LoginRequest.swift
  Memento-iOS/Memento-iOS/Source/Network/Onboarding/DTO/Response /LoginResponse.swift
  Memento-iOS/Memento-iOS/Source/Network/Onboarding/DTO/Response /NewAccessTokenResponse.swift
  Memento-iOS/Memento-iOS/Source/Network/Onboarding/LoginAPIService.swift
  Memento-iOS/Memento-iOS/Source/Network/Onboarding/LoginTargetType.swift
  Memento-iOS/Memento-iOS/Source/Network/Onboarding/TokenRefreshType.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/Model/SurveyQuestion.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/View/CalendarConnectView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/View/LoginView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/ViewModel/AuthViewModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/ViewModel/OnboardingViewModel.swift
Labels: Feat, 정욱, Network

#83 [Network] #71 - Schedule detail API sub connect
  Memento-iOS/Memento-iOS/Source/Component/MementoCell/ColorTagView.swift
  Memento-iOS/Memento-iOS/Source/Component/MementoCell/ScheduleListCell.swift
  Memento-iOS/Memento-iOS/Source/Component/TabBar/TabBarItem.swift
  Memento-iOS/Memento-iOS/Source/Extension/Color+.swift
  Memento-iOS/Memento-iOS/Source/Network/Schedule/DTO/Response/ScheduleDetailResponseData.swift
  Memento-iOS/Memento-iOS/Source/Network/Schedule/DTO/Response/ScheduleResponseData.swift
  Memento-iOS/Memento-iOS/Source/Network/Schedule/DTO/Response/ScheduleTotalResponseData.swift
  Memento-iOS/Memento-iOS/Source/Network/Schedule/ScheduleAPIService.swift
  Memento-iOS/Memento-iOS/Source/Network/Schedule/ScheduleTargetType.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/Model/TodayItemDataModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/View/ToDoList/ToDoListView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/View/ToDoList/ToDoListWeeklyCalendarView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/View/Today/TodayView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/View/Today/TodayWeeklyCalendarView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/ViewModel/WeeklyCalendarViewModel.swift
Labels: 가현, Network

#85 [Network] #84 - Tags API connect
  Memento-iOS/Memento-iOS/Source/Component/TabBar/TabBarItem.swift
  Memento-iOS/Memento-iOS/Source/Network/Tag/DTO/Response/TagResponseData.swift
  Memento-iOS/Memento-iOS/Source/Network/Tag/TagAPIService.swift
  Memento-iOS/Memento-iOS/Source/Network/Tag/TagTargetType.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/Model/ToDoListDataModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/View/Today/TodayWeeklyCalendarView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/ViewModel/WeeklyCalendarViewModel.swift
Labels: 가현, Network

#87 [Network] #76 - TODO 생성 API 연결
  Memento-iOS/Memento-iOS.xcodeproj/project.pbxproj
  Memento-iOS/Memento-iOS/Source/Network/Todo/DTO/Request/TodoRequest.swift
  Memento-iOS/Memento-iOS/Source/Network/Todo/TodoAPIService.swift
  Memento-iOS/Memento-iOS/Source/Network/Todo/TodoTargetType.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddSchedule/ViewModel/AddSchedulePickerButtonViewModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddTodo/View/AddTagView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddTodo/View/AddTodoBottomView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddTodo/View/AddTodoView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddTodo/ViewModel/AddTodoHeaderViewModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddTodo/ViewModel/AddTodoPickerButtonViewModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddTodo/ViewModel/AddTodoViewModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/Tag/Model/Tag.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/Tag/View/TagListView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/View/Today/TodayView.swift
Labels: Feat, 범수, Network

#88 [Feat] #86 - Quarterly processing of data by date
  Memento-iOS/Memento-iOS/Source/Component/MementoCell/ScheduleListCell.swift
  Memento-iOS/Memento-iOS/Source/Network/Schedule/DTO/Response/ScheduleTotalResponseData.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/View/Today/TodayView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/View/Today/TodayWeeklyCalendarView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/ViewModel/WeeklyCalendarViewModel.swift
Labels: 가현, Network

#90 Feat/#78 Login 이후 화면 전환 작업 및 Onboarding 관련 API 연결
  Memento-iOS/Memento-iOS.xcodeproj/project.pbxproj
  Memento-iOS/Memento-iOS/Source/App/Memento_iOSApp.swift
  Memento-iOS/Memento-iOS/Source/Const/StringLiteral.swift
  Memento-iOS/Memento-iOS/Source/Network/Base/BaseTargetType.swift
  Memento-iOS/Memento-iOS/Source/Network/Base/TokenKeychainManager.swift
  Memento-iOS/Memento-iOS/Source/Network/Base/TokenRefreshPlugin.swift
  Memento-iOS/Memento-iOS/Source/Network/Onboarding/AppleSchedulesAPIService.swift
  Memento-iOS/Memento-iOS/Source/Network/Onboarding/DTO/Request/AppleScheduleListRequest.swift
  Memento-iOS/Memento-iOS/Source/Network/Onboarding/DTO/Request/UserInfoRequest.swift
  Memento-iOS/Memento-iOS/Source/Network/Onboarding/DTO/Response /NewAccessTokenResponse.swift
  Memento-iOS/Memento-iOS/Source/Network/Onboarding/DTO/Response /UserUptimeResponse.swift
  Memento-iOS/Memento-iOS/Source/Network/Onboarding/DTO/TargetType/AppleSchedulesTargetType.swift
  Memento-iOS/Memento-iOS/Source/Network/Onboarding/DTO/TargetType/LoginTargetType.swift
  Memento-iOS/Memento-iOS/Source/Network/Onboarding/DTO/TargetType/TokenRefreshType.swift
  Memento-iOS/Memento-iOS/Source/Network/Onboarding/DTO/TargetType/UserInfoTargetType.swift
  Memento-iOS/Memento-iOS/Source/Network/Onboarding/DTO/TargetType/UserUptimeTargetType.swift
  Memento-iOS/Memento-iOS/Source/Network/Onboarding/UserInfoAPIService.swift
  Memento-iOS/Memento-iOS/Source/Network/Onboarding/UserUptimeAPIService.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddTodo/View/AddTodoView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/Model/Category.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/Model/SleepCycleRequestModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/View/CalendarConnectView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/View/LoginView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/View/SleepCycleSettingView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/View/WorkSelectionView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/ViewModel/AppState.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/ViewModel/OnboardingViewModel.swift
Labels: Feat, 정욱, Network

#92 [Network] #89 - All day api connect
  Memento-iOS/Memento-iOS/Source/Component/MementoCell/AllDayListCell.swift
  Memento-iOS/Memento-iOS/Source/Network/Schedule/DTO/Response/ScheduleAllDayResponseData.swift
  Memento-iOS/Memento-iOS/Source/Network/Schedule/DTO/Response/ScheduleTotalResponseData.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/View/Today/AllDayListView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/View/Today/TodayWeeklyCalendarView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/ViewModel/WeeklyCalendarViewModel.swift
Labels: 가현, Network

#94 [Network] #91 - TODO 생성 API 구현
  Memento-iOS/Memento-iOS.xcodeproj/project.pbxproj
  Memento-iOS/Memento-iOS/Source/Component/EisenhowerMatrixView.swift
  Memento-iOS/Memento-iOS/Source/Component/MementoCell/PriorityLabel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddTodo/View/AddTodoBottomView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddTodo/View/AddTodoView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddTodo/ViewModel/AddTodoViewModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/ViewType/ViewType.swift
Labels: Feat, 범수, Network

#97 [Design] #96 - Lottie fix
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/View/Launch Screen.storyboard
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/View/LottieView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/View/SplashScreenView.swift
Labels: 가현

#105 Feat/#101 - Floating Button 구현 및 AI 관련 Api 연동
  Memento-iOS/Memento-iOS.xcodeproj/project.pbxproj
  Memento-iOS/Memento-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Memento-iOS/Memento-iOS/Source/App/Memento_iOSApp.swift
  Memento-iOS/Memento-iOS/Source/Component/RefreshAnimationView.swift
  Memento-iOS/Memento-iOS/Source/Network/AI/DTO/Request/PrioritizationRequest.swift
  Memento-iOS/Memento-iOS/Source/Network/AI/DTO/Response/PrioritizationResponse.swift
  Memento-iOS/Memento-iOS/Source/Network/AI/PrioritizationAPIService.swift
  Memento-iOS/Memento-iOS/Source/Network/AI/TargetType/PrioritizationTargetType.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/View/Today/TodayView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/View/CalendarConnectView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/View/SplashScreenView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Onboarding/ViewModel/AppState.swift
Labels: Feat, 정욱, Network

#111 [Feat] #109 - 바텀 시트 내리기 구현 및 버그 해결
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddTodo/ViewModel/AddTodoPickerButtonViewModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/AddTodo/ViewModel/AddTodoViewModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/Tag/Model/Tag.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/Tag/View/TagPickerButton.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Add/Common/Tag/View/TagPickerSheetView.swift
Labels: Feat, 범수

#115 [Network] #82 - ToDoList 반환 API 연결
  Memento-iOS/Memento-iOS.xcodeproj/project.pbxproj
  Memento-iOS/Memento-iOS/Source/App/Memento_iOSApp.swift
  Memento-iOS/Memento-iOS/Source/Component/MementoCell/ToDoListCell.swift
  Memento-iOS/Memento-iOS/Source/Component/TabBar/TabBarItem.swift
  Memento-iOS/Memento-iOS/Source/Component/TabBar/TabBarView.swift
  Memento-iOS/Memento-iOS/Source/Network/Base/BaseAPIService.swift
  Memento-iOS/Memento-iOS/Source/Network/ToDoList/DTO/Response/ToDoListCompletedResponseData.swift
  Memento-iOS/Memento-iOS/Source/Network/ToDoList/DTO/Response/ToDoListResponseData.swift
  Memento-iOS/Memento-iOS/Source/Network/ToDoList/ToDoListAPIService.swift
  Memento-iOS/Memento-iOS/Source/Network/ToDoList/ToDoListTargetType.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/Model/ToDoListDataModel.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/View/ToDoList/ToDoListItemView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/View/ToDoList/ToDoListView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/View/ToDoList/ToDoListWeeklyCalendarView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/View/Today/TodayWeeklyCalendarView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/ViewModel/WeeklyCalendarViewModel.swift
Labels: 세민, Network

#117 [Network] #112 - Delete API Connected
  Memento-iOS/Memento-iOS/Source/Component/Alert/ScheduleAlertView.swift
  Memento-iOS/Memento-iOS/Source/Component/Alert/ToDoAlertView.swift
  Memento-iOS/Memento-iOS/Source/Network/Schedule/ScheduleAPIService.swift
  Memento-iOS/Memento-iOS/Source/Network/Schedule/ScheduleTargetType.swift
  Memento-iOS/Memento-iOS/Source/Network/Todo/TodoAPIService.swift
  Memento-iOS/Memento-iOS/Source/Network/Todo/TodoTargetType.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/View/ToDoList/ToDoListView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/View/Today/TodayView.swift
Labels: 범수, Network

#120 [Network] # 98 - ToDoList 체크 (완료여부) API
  Memento-iOS/Memento-iOS/Source/Component/MementoCell/ToDoListCell.swift
  Memento-iOS/Memento-iOS/Source/Network/ToDoList/DTO/Response/ToDoListResponseData.swift
  Memento-iOS/Memento-iOS/Source/Network/ToDoList/ToDoListAPIService.swift
  Memento-iOS/Memento-iOS/Source/Network/ToDoList/ToDoListTargetType.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/View/ToDoList/ToDoListItemView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/View/ToDoList/ToDoListView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/View/Today/TodayView.swift
  Memento-iOS/Memento-iOS/Source/Presentation/Main/ViewModel/WeeklyCalendarViewModel.swift
Labels: 세민, Network
